### ISSUE TITLE
Failed to resolve: com.github.makbn:analog-clock-with-second:-SNAPSHOT

### ISSUE THREAD

**Issue by maheshmnj** [makbn/analog-clock-with-second#1]
I am very excited to integrate this library with my project but it fails,I have added the maven as well but sadly I get the error while I Sync :(

**Comment by makbn** [comment]
Readme file is updated! use new version:

`implementation 'com.github.makbn:analog-clock-with-second:master'`

sorry but I recommend you to use source code instead of adding the library because ill not maintain this project anymore!
